			 SELECT
				DISTINCT
				EMP.EMP_CODIGO AS value,
			    ISYSEPQ.GETNOMBRECOMPLETOEMPLEADO(EMP.EMP_CODIGO) AS label
			FROM PLA_GER_GERENCIA GER
			JOIN PLA_UNI_UNIDAD UNI ON GER.GER_CODCIA = UNI.UNI_CODCIA AND GER.GER_CODIGO = UNI.UNI_CODUNI_PADRE
			JOIN PLA_PLZ_PLAZA PLZ ON UNI.UNI_CODCIA = PLZ.PLZ_CODCIA AND UNI.UNI_CODIGO = PLZ.PLZ_CODUNI
			JOIN PLA_DPL_DATOSPLANILLA DPL ON PLZ.PLZ_CODCIA = DPL.DPL_CODCIA AND PLZ.PLZ_CODIGO = DPL.DPL_CODPLZ
			JOIN PLA_EMP_EMPLEADO EMP ON DPL.DPL_CODCIA = EMP.EMP_CODCIA AND DPL.DPL_CODEMP = EMP.EMP_CODIGO
			WHERE UNI.UNI_CODIGO = pEmpCoduniUbi
			ORDER BY ISYSEPQ.GETNOMBRECOMPLETOEMPLEADO(EMP_CODIGO);